lecture-2/hw done
Remzes/react-20231109 pull request #2
Opened 2023-11-20 00:25 UTC by Remzes

ДЗ 2

2023-11-20 17:08 UTC, SArchieEdu requested changes
нужно доделать

2023-11-20 17:08 UTC, SArchieEdu commented on src/pages/restaurants/index.jsx
> +            <Navbar items={items} />
Лучше более конкретно назвать

2023-11-20 17:08 UTC, SArchieEdu commented on src/components/menu/index.jsx
> +                        <p>{ingredients}</p>
Лучше в отдельный компонент

2023-11-20 17:08 UTC, SArchieEdu commented on src/components/reviews/index.jsx
> +                        <p>{text}</p>
Лучше в отдельный компонент

2023-11-25 12:06 UTC, Remzes commented on src/components/reviews/index.jsx
> +                        <p>{text}</p>
fixed

2023-11-25 12:06 UTC, Remzes commented on src/components/menu/index.jsx
> +                        <p>{ingredients}</p>
fixed

2023-11-25 12:06 UTC, Remzes commented on src/pages/restaurants/index.jsx
> +            <Navbar items={items} />
fixed

2023-11-25 12:06 UTC, merged